# Data Manipulation Exercise

Write a program that:

1) loads the file into a pandas dataframe 

2) groups the data to calculate mean revenues (revt) by firm-year

3) merge this value back into the main data file and create a deviation score (focal – mean)

4) lag revenues and create a change score (current – lagged revenues)

5) correlate lagged and current revenues 

6) create a binary variable for whether the company name includes “.com”, case-insensitive 

7) group on this variable and get the mean market value (prcc_c * csho) for each group

In [87]:
#import package
import pandas as pd
import re

In [88]:
#loads the file into a pandas dataframe
df = pd.read_stata('compustat_exercise.dta')
print(df.shape, df.columns.to_list())
df.head(50)

(37750, 10) ['gvkey', 'fyear', 'conm', 'naics', 'city', 'state', 'revt', 'csho', 'prcc_c', 'busdesc']

,gvkey,fyear,conm,naics,city,state,revt,csho,prcc_c,busdesc
0,1004,2012.0,AAR CORP,423860.0,Wood Dale,IL,2167.100,39.382,18.680,AAR CORP. provides products and services to co...
1,1004,2013.0,AAR CORP,423860.0,Wood Dale,IL,2035.000,39.560,28.010,AAR CORP. provides products and services to co...
2,1004,2014.0,AAR CORP,423860.0,Wood Dale,IL,1594.300,35.423,27.780,AAR CORP. provides products and services to co...
3,1045,2012.0,AMERICAN AIRLINES GROUP INC,481111.0,Fort Worth,TX,24855.000,335.292,0.795,"American Airlines Group Inc., through its subs..."
4,1045,2013.0,AMERICAN AIRLINES GROUP INC,481111.0,Fort Worth,TX,26712.000,261.069,25.250,"American Airlines Group Inc., through its subs..."
5,1045,2014.0,AMERICAN AIRLINES GROUP INC,481111.0,Fort Worth,TX,42650.000,697.475,53.630,"American Airlines Group Inc., through its subs..."
6,1050,2012.0,CECO ENVIRONMENTAL CORP,333413.0,Cincinnati,OH,135.052,16.959,9.950,"CECO Environmental Corp., an environmental tec..."
7,1050,2013.0,CECO ENVIRONMENTAL CORP,333413.0,Cincinnati,OH,197.317,25.587,16.152,"CECO Environmental Corp., an environmental tec..."
8,1050,2014.0,CECO ENVIRONMENTAL CORP,333413.0,Cincinnati,OH,263.217,26.267,15.540,"CECO Environmental Corp., an environmental tec..."
9,1062,2012.0,ASA GOLD AND PRECIOUS METALS,523999.0,San Mateo,CA,5.817,19.290,21.530,ASA Gold and Precious Metals Limited is a self...
10,1062,2012.0,ASA GOLD AND PRECIOUS METALS,523999.0,San Mateo,CA,45.498,NaN,21.530,ASA Gold and Precious Metals Limited is a self...
11,1062,2013.0,ASA GOLD AND PRECIOUS METALS,523999.0,San Mateo,CA,-2.926,NaN,12.260,ASA Gold and Precious Metals Limited is a self...
12,1062,2013.0,ASA GOLD AND PRECIOUS METALS,523999.0,San Mateo,CA,4.481,19.290,12.260,ASA Gold and Precious Metals Limited is a self...
13,1062,2014.0,ASA GOLD AND PRECIOUS METALS,523999.0,San Mateo,CA,-7.048,NaN,10.110,ASA Gold and Precious Metals Limited is a self...
14,1062,2014.0,ASA GOLD AND PRECIOUS METALS,523999.0,San Mateo,CA,2.219,19.290,10.110,ASA Gold and Precious Metals Limited is a self...
15,1072,2012.0,AVX CORP,334416.0,Fountain Inn,SC,1414.400,168.633,10.780,"AVX Corporation, together with its subsidiarie..."
16,1072,2013.0,AVX CORP,334416.0,Fountain Inn,SC,1442.604,168.221,13.930,"AVX Corporation, together with its subsidiarie..."
17,1072,2014.0,AVX CORP,334416.0,Fountain Inn,SC,1353.228,168.190,14.000,"AVX Corporation, together with its subsidiarie..."
18,1075,2012.0,PINNACLE WEST CAPITAL CORP,2211.0,Phoenix,AZ,3301.804,109.743,50.980,"Pinnacle West Capital Corporation, through its..."
19,1075,2013.0,PINNACLE WEST CAPITAL CORP,2211.0,Phoenix,AZ,3454.628,110.182,52.920,"Pinnacle West Capital Corporation, through its..."
20,1075,2014.0,PINNACLE WEST CAPITAL CORP,2211.0,Phoenix,AZ,3491.632,110.571,68.310,"Pinnacle West Capital Corporation, through its..."
21,1076,2012.0,AARON'S INC,532299.0,Atlanta,GA,2222.588,75.720,28.280,"Aaron's, Inc. operates as a specialty retailer..."
22,1076,2013.0,AARON'S INC,532299.0,Atlanta,GA,2234.631,72.957,29.400,"Aaron's, Inc. operates as a specialty retailer..."
23,1076,2014.0,AARON'S INC,532299.0,Atlanta,GA,2725.239,72.488,30.570,"Aaron's, Inc. operates as a specialty retailer..."
24,1078,2012.0,ABBOTT LABORATORIES,325412.0,Abbott Park,IL,39873.910,1576.667,65.500,Abbott Laboratories manufactures and sells hea...
25,1078,2013.0,ABBOTT LABORATORIES,325412.0,Abbott Park,IL,21848.000,1548.098,38.330,Abbott Laboratories manufactures and sells hea...
26,1078,2014.0,ABBOTT LABORATORIES,325412.0,Abbott Park,IL,20247.000,1508.035,45.020,Abbott Laboratories manufactures and sells hea...
27,1084,2012.0,WORLDS INC,519130.0,Brookline,MA,0.000,79.813,0.200,"Worlds Inc. designs and develops software, con..."
28,1084,2013.0,WORLDS INC,519130.0,Brookline,MA,0.000,93.210,0.150,"Worlds Inc. designs and develops software, con..."
29,1084,2014.0,WORLDS INC,519130.0,Brookline,MA,0.000,96.852,0.145,"Worlds Inc. designs and develops software, con..."
30,1094,2012.0,ACETO CORP,424690.0,Port Washington,NY,444.388,26.937,10.050,"Aceto Corporation, together with its subsidiar..."
31,1094,2013.0,ACETO CORP,424690.0,Port Washington,NY,499.690,27.831,25.010,"Aceto Corporation, together with its subsidiar..."
32,1094,2014.0,ACETO CORP,424690.0,Port Washington,NY,510.179,28.772,21.700,"Aceto Corporation, together with its subsidiar..."
33,1096,2012.0,MORGUARD CORP,531.0,Mississauga,ON,415.917,12.772,114.600,"Morguard Corporation, a real estate investment..."
34,1096,2013.0,MORGUARD CORP,531.0,Mississauga,ON,516.882,12.586,125.390,"Morguard Corporation, a real estate investment..."
35,1096,2014.0,MORGUARD CORP,531.0,Mississauga,ON,566.326,12.353,150.000,"Morguard Corporation, a real estate investment..."
36,1097,2012.0,ACMAT CORP -CL A,524126.0,Farmington,CT,6.003,1.166,22.000,"ACMAT Corporation, through its subsidiaries, p..."
37,1097,2013.0,ACMAT CORP -CL A,524126.0,Farmington,CT,5.547,1.072,24.000,"ACMAT Corporation, through its subsidiaries, p..."
38,1097,2014.0,ACMAT CORP -CL A,524126.0,Farmington,CT,5.102,1.006,21.000,"ACMAT Corporation, through its subsidiaries, p..."
39,1104,2012.0,ACME UNITED CORP,332215.0,Fairfield,CT,84.370,3.125,11.040,"Acme United Corporation, together with its sub..."
40,1104,2013.0,ACME UNITED CORP,332215.0,Fairfield,CT,89.577,3.201,14.900,"Acme United Corporation, together with its sub..."
41,1104,2014.0,ACME UNITED CORP,332215.0,Fairfield,CT,107.222,3.291,19.990,"Acme United Corporation, together with its sub..."
42,1117,2012.0,RELM WIRELESS CORP,334220.0,West Melbourne,FL,27.576,13.545,1.680,"RELM Wireless Corporation designs, manufacture..."
43,1117,2013.0,RELM WIRELESS CORP,334220.0,West Melbourne,FL,27.023,13.589,3.370,"RELM Wireless Corporation designs, manufacture..."
44,1117,2014.0,RELM WIRELESS CORP,334220.0,West Melbourne,FL,30.971,13.665,4.800,"RELM Wireless Corporation designs, manufacture..."
45,1119,2012.0,ADAMS DIVERSIFIED EQUITY FD,525990.0,Baltimore,MD,NaN,91.106,10.590,"Adams Diversified Equity Fund, Inc. is a self ..."
46,1119,2013.0,ADAMS DIVERSIFIED EQUITY FD,525990.0,Baltimore,MD,NaN,92.216,13.070,"Adams Diversified Equity Fund, Inc. is a self ..."
47,1119,2014.0,ADAMS DIVERSIFIED EQUITY FD,525990.0,Baltimore,MD,NaN,93.509,13.680,"Adams Diversified Equity Fund, Inc. is a self ..."
48,1121,2012.0,ADAMS RESOURCES & ENERGY INC,424720.0,Houston,TX,3380.964,4.218,35.070,"Adams Resources & Energy, Inc., through its su..."
49,1121,2013.0,ADAMS RESOURCES & ENERGY INC,424720.0,Houston,TX,3945.969,4.218,68.500,"Adams Resources & Energy, Inc., through its su..."

In [89]:
#groups the data to calculate mean revenues (revt) by firm-year
df2 = df.groupby('fyear')['revt'].mean()

In [90]:
#merge this value back into the main data file 
df3 = df.merge(df2, on='fyear')
df3

,gvkey,fyear,conm,naics,city,state,revt_x,csho,prcc_c,busdesc,revt_y
0,1004,2012.0,AAR CORP,423860.0,Wood Dale,IL,2167.100,39.382,18.680,AAR CORP. provides products and services to co...,3224.339204
1,1045,2012.0,AMERICAN AIRLINES GROUP INC,481111.0,Fort Worth,TX,24855.000,335.292,0.795,"American Airlines Group Inc., through its subs...",3224.339204
2,1050,2012.0,CECO ENVIRONMENTAL CORP,333413.0,Cincinnati,OH,135.052,16.959,9.950,"CECO Environmental Corp., an environmental tec...",3224.339204
3,1062,2012.0,ASA GOLD AND PRECIOUS METALS,523999.0,San Mateo,CA,5.817,19.290,21.530,ASA Gold and Precious Metals Limited is a self...,3224.339204
4,1062,2012.0,ASA GOLD AND PRECIOUS METALS,523999.0,San Mateo,CA,45.498,NaN,21.530,ASA Gold and Precious Metals Limited is a self...,3224.339204
...,...,...,...,...,...,...,...,...,...,...,...
37745,316056,2014.0,ALLEGION PLC,332510.0,Dublin,,2118.300,95.831,55.460,Allegion Public Limited Company manufactures a...,3451.595388
37746,316461,2014.0,AGILITY HEALTH INC,621340.0,Grand Rapids,,62.105,81.964,NaN,"Agility Health, Inc. provides rehabilitation s...",3451.595388
37747,317260,2014.0,NORDIC AMERICAN OFFSHORE,483111.0,Hamilton,,52.789,23.431,12.280,Nordic American Offshore Ltd. owns and operate...,3451.595388
37748,317264,2014.0,DORIAN LPG LTD,483111.0,Stamford,,104.129,58.057,13.890,Dorian LPG Ltd. operates as a liquefied petrol...,3451.595388
37749,318970,2014.0,NYX GAMING GROUP LTD,5415.0,Saint Peter Port,,27.278,33.800,NaN,"NYX Gaming Group Limited designs, develops, ma...",3451.595388

In [91]:
#create a deviation score (focal – mean)
df3['devscore']= df3['revt_x'] - df3['revt_y']
df3.head()

,gvkey,fyear,conm,naics,city,state,revt_x,csho,prcc_c,busdesc,revt_y,devscore
0,1004,2012.0,AAR CORP,423860.0,Wood Dale,IL,2167.100,39.382,18.680,AAR CORP. provides products and services to co...,3224.339204,-1057.239204
1,1045,2012.0,AMERICAN AIRLINES GROUP INC,481111.0,Fort Worth,TX,24855.000,335.292,0.795,"American Airlines Group Inc., through its subs...",3224.339204,21630.660796
2,1050,2012.0,CECO ENVIRONMENTAL CORP,333413.0,Cincinnati,OH,135.052,16.959,9.950,"CECO Environmental Corp., an environmental tec...",3224.339204,-3089.287204
3,1062,2012.0,ASA GOLD AND PRECIOUS METALS,523999.0,San Mateo,CA,5.817,19.290,21.530,ASA Gold and Precious Metals Limited is a self...,3224.339204,-3218.522204
4,1062,2012.0,ASA GOLD AND PRECIOUS METALS,523999.0,San Mateo,CA,45.498,NaN,21.530,ASA Gold and Precious Metals Limited is a self...,3224.339204,-3178.841204

In [92]:
#lag revenues - sorting values   
df3.sort_values(by=['conm','fyear'], inplace=True)
df3.head()

,gvkey,fyear,conm,naics,city,state,revt_x,csho,prcc_c,busdesc,revt_y,devscore
6966,132602,2012.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,0.934,64.564,1.060,01 Communique Laboratory Inc. develops and mar...,3224.339204,-3223.405204
20063,132602,2013.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,1.258,65.204,0.345,01 Communique Laboratory Inc. develops and mar...,3269.491162,-3268.233162
32581,132602,2014.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,0.267,65.744,0.195,01 Communique Laboratory Inc. develops and mar...,3451.595388,-3451.328388
6762,122519,2012.0,1-800-FLOWERS.COM,453110.0,Carle Place,NY,716.257,64.556,3.670,"1-800-FLOWERS.COM, Inc. operates a florist and...",3224.339204,-2508.082204
19868,122519,2013.0,1-800-FLOWERS.COM,453110.0,Carle Place,NY,735.497,63.868,5.410,"1-800-FLOWERS.COM, Inc. operates a florist and...",3269.491162,-2533.994162

In [103]:
#lag revenues - creating new variable
df3['revt1'] = df3.groupby('conm').revt_x.shift(1)
df3.head(50)

,gvkey,fyear,conm,naics,city,state,revt_x,csho,prcc_c,busdesc,revt_y,devscore,revt1,change_score
6966,132602,2012.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,0.934,64.564,1.060,01 Communique Laboratory Inc. develops and mar...,3224.339204,-3223.405204,NaN,NaN
20063,132602,2013.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,1.258,65.204,0.345,01 Communique Laboratory Inc. develops and mar...,3269.491162,-3268.233162,0.934,0.324
32581,132602,2014.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,0.267,65.744,0.195,01 Communique Laboratory Inc. develops and mar...,3451.595388,-3451.328388,1.258,-0.991
6762,122519,2012.0,1-800-FLOWERS.COM,453110.0,Carle Place,NY,716.257,64.556,3.670,"1-800-FLOWERS.COM, Inc. operates a florist and...",3224.339204,-2508.082204,NaN,NaN
19868,122519,2013.0,1-800-FLOWERS.COM,453110.0,Carle Place,NY,735.497,63.868,5.410,"1-800-FLOWERS.COM, Inc. operates a florist and...",3269.491162,-2533.994162,716.257,19.240
32397,122519,2014.0,1-800-FLOWERS.COM,453110.0,Carle Place,NY,756.345,64.080,8.240,"1-800-FLOWERS.COM, Inc. operates a florist and...",3451.595388,-2695.250388,735.497,20.848
28953,20517,2014.0,1347 CAPITAL CORP,999990.0,Itasca,IL,NaN,1.848,9.586,1347 Capital Corp. does not have significant o...,3451.595388,NaN,NaN,NaN
3006,19528,2012.0,1347 PROPERTY INS HLDGS INC,524126.0,Tampa,FL,NaN,1.000,NaN,"1347 Property Insurance Holdings, Inc., throug...",3224.339204,NaN,NaN,NaN
16092,19528,2013.0,1347 PROPERTY INS HLDGS INC,524126.0,Tampa,FL,5.091,1.000,NaN,"1347 Property Insurance Holdings, Inc., throug...",3269.491162,-3264.400162,NaN,NaN
28643,19528,2014.0,1347 PROPERTY INS HLDGS INC,524126.0,Tampa,FL,18.965,6.358,7.860,"1347 Property Insurance Holdings, Inc., throug...",3451.595388,-3432.630388,5.091,13.874
10090,177646,2012.0,1ST CAPITAL BANK,522110.0,Monterey,CA,13.510,3.311,10.750,1st Capital Bank provides various banking prod...,3224.339204,-3210.829204,NaN,NaN
10091,177646,2012.0,1ST CAPITAL BANK,522110.0,Monterey,CA,13.510,NaN,10.750,1st Capital Bank provides various banking prod...,3224.339204,-3210.829204,13.510,0.000
22979,177646,2013.0,1ST CAPITAL BANK,522110.0,Monterey,CA,13.397,3.497,11.330,1st Capital Bank provides various banking prod...,3269.491162,-3256.094162,13.510,-0.113
22980,177646,2013.0,1ST CAPITAL BANK,522110.0,Monterey,CA,13.397,NaN,11.330,1st Capital Bank provides various banking prod...,3269.491162,-3256.094162,13.397,0.000
12813,264418,2012.0,1ST CENTURY BANCSHARES INC,522110.0,Los Angeles,CA,17.025,9.137,4.611,"1st Century Bancshares, Inc. operates as a ban...",3224.339204,-3207.314204,NaN,NaN
12814,264418,2012.0,1ST CENTURY BANCSHARES INC,522110.0,Los Angeles,CA,17.025,NaN,4.611,"1st Century Bancshares, Inc. operates as a ban...",3224.339204,-3207.314204,17.025,0.000
25536,264418,2013.0,1ST CENTURY BANCSHARES INC,522110.0,Los Angeles,CA,18.809,9.481,7.150,"1st Century Bancshares, Inc. operates as a ban...",3269.491162,-3250.682162,17.025,1.784
25537,264418,2013.0,1ST CENTURY BANCSHARES INC,522110.0,Los Angeles,CA,18.809,NaN,7.150,"1st Century Bancshares, Inc. operates as a ban...",3269.491162,-3250.682162,18.809,0.000
37610,264418,2014.0,1ST CENTURY BANCSHARES INC,522110.0,Los Angeles,CA,20.926,10.140,6.350,"1st Century Bancshares, Inc. operates as a ban...",3451.595388,-3430.669388,18.809,2.117
37611,264418,2014.0,1ST CENTURY BANCSHARES INC,522110.0,Los Angeles,CA,20.926,NaN,6.350,"1st Century Bancshares, Inc. operates as a ban...",3451.595388,-3430.669388,20.926,0.000
5590,65467,2012.0,1ST CONSTITUTION BANCORP,522110.0,Cranbury,NJ,38.104,5.978,8.760,1st Constitution Bancorp operates as the holdi...,3224.339204,-3186.235204,NaN,NaN
5591,65467,2012.0,1ST CONSTITUTION BANCORP,522110.0,Cranbury,NJ,38.104,NaN,8.760,1st Constitution Bancorp operates as the holdi...,3224.339204,-3186.235204,38.104,0.000
18774,65467,2013.0,1ST CONSTITUTION BANCORP,522110.0,Cranbury,NJ,34.819,NaN,11.000,1st Constitution Bancorp operates as the holdi...,3269.491162,-3234.672162,38.104,-3.285
18775,65467,2013.0,1ST CONSTITUTION BANCORP,522110.0,Cranbury,NJ,34.819,6.017,11.000,1st Constitution Bancorp operates as the holdi...,3269.491162,-3234.672162,34.819,0.000
31391,65467,2014.0,1ST CONSTITUTION BANCORP,522110.0,Cranbury,NJ,43.124,7.134,10.890,1st Constitution Bancorp operates as the holdi...,3451.595388,-3408.471388,34.819,8.305
31392,65467,2014.0,1ST CONSTITUTION BANCORP,522110.0,Cranbury,NJ,43.124,NaN,10.890,1st Constitution Bancorp operates as the holdi...,3451.595388,-3408.471388,43.124,0.000
9510,175290,2012.0,1ST ENTERPRISE BANK,522110.0,Los Angeles,CA,23.623,3.815,15.300,"As of November 30, 2014, 1st Enterprise Bank w...",3224.339204,-3200.716204,NaN,NaN
9511,175290,2012.0,1ST ENTERPRISE BANK,522110.0,Los Angeles,CA,23.623,NaN,15.300,"As of November 30, 2014, 1st Enterprise Bank w...",3224.339204,-3200.716204,23.623,0.000
22427,175290,2013.0,1ST ENTERPRISE BANK,522110.0,Los Angeles,CA,26.183,3.824,19.300,"As of November 30, 2014, 1st Enterprise Bank w...",3269.491162,-3243.308162,23.623,2.560
22428,175290,2013.0,1ST ENTERPRISE BANK,522110.0,Los Angeles,CA,26.183,NaN,19.300,"As of November 30, 2014, 1st Enterprise Bank w...",3269.491162,-3243.308162,26.183,0.000
2034,15199,2012.0,1ST SOURCE CORP,522110.0,South Bend,IN,263.277,24.243,22.090,1st Source Corporation operates as the bank ho...,3224.339204,-2961.062204,NaN,NaN
2035,15199,2012.0,1ST SOURCE CORP,522110.0,South Bend,IN,263.277,NaN,22.090,1st Source Corporation operates as the bank ho...,3224.339204,-2961.062204,263.277,0.000
14905,15199,2013.0,1ST SOURCE CORP,522110.0,South Bend,IN,256.797,NaN,31.940,1st Source Corporation operates as the bank ho...,3269.491162,-3012.694162,263.277,-6.480
14906,15199,2013.0,1ST SOURCE CORP,522110.0,South Bend,IN,256.797,24.323,31.940,1st Source Corporation operates as the bank ho...,3269.491162,-3012.694162,256.797,0.000
27524,15199,2014.0,1ST SOURCE CORP,522110.0,South Bend,IN,256.441,23.862,34.310,1st Source Corporation operates as the bank ho...,3451.595388,-3195.154388,256.797,-0.356
27525,15199,2014.0,1ST SOURCE CORP,522110.0,South Bend,IN,256.441,NaN,34.310,1st Source Corporation operates as the bank ho...,3451.595388,-3195.154388,256.441,0.000
10530,179586,2012.0,1ST UNITED BANCORP INC,522110.0,Boca Raton,FL,70.183,34.070,6.250,"1st United Bancorp, Inc. was acquired by Valle...",3224.339204,-3154.156204,NaN,NaN
10531,179586,2012.0,1ST UNITED BANCORP INC,522110.0,Boca Raton,FL,70.183,NaN,6.250,"1st United Bancorp, Inc. was acquired by Valle...",3224.339204,-3154.156204,70.183,0.000
23397,179586,2013.0,1ST UNITED BANCORP INC,522110.0,Boca Raton,FL,71.500,34.289,7.610,"1st United Bancorp, Inc. was acquired by Valle...",3269.491162,-3197.991162,70.183,1.317
23398,179586,2013.0,1ST UNITED BANCORP INC,522110.0,Boca Raton,FL,71.500,NaN,7.610,"1st United Bancorp, Inc. was acquired by Valle...",3269.491162,-3197.991162,71.500,0.000
16362,20547,2013.0,2050 MOTORS INC,441110.0,Las Vegas,NV,NaN,NaN,NaN,"2050 Motors, Inc., a development stage company...",3269.491162,NaN,NaN,NaN
28965,20547,2014.0,2050 MOTORS INC,441110.0,Las Vegas,NV,0.000,33.438,1.450,"2050 Motors, Inc., a development stage company...",3451.595388,-3451.595388,NaN,NaN
12831,265008,2012.0,21ST CENTURY ONCOLOGY HLDGS,621498.0,Fort Myers,FL,693.951,0.001,NaN,"21st Century Oncology Holdings, Inc., together...",3224.339204,-2530.388204,NaN,NaN
25554,265008,2013.0,21ST CENTURY ONCOLOGY HLDGS,621498.0,Fort Myers,FL,736.516,0.001,NaN,"21st Century Oncology Holdings, Inc., together...",3269.491162,-2532.975162,693.951,42.565
37626,265008,2014.0,21ST CENTURY ONCOLOGY HLDGS,621498.0,Fort Myers,FL,1026.422,0.001,NaN,"21st Century Oncology Holdings, Inc., together...",3451.595388,-2425.173388,736.516,289.906
12125,186876,2012.0,21VIANET GROUP INC,519130.0,Beijing,,244.644,57.833,9.610,"21Vianet Group, Inc. provides carrier-neutral ...",3224.339204,-2979.695204,NaN,NaN
24892,186876,2013.0,21VIANET GROUP INC,519130.0,Beijing,,324.879,66.371,23.520,"21Vianet Group, Inc. provides carrier-neutral ...",3269.491162,-2944.612162,244.644,80.235
37014,186876,2014.0,21VIANET GROUP INC,519130.0,Beijing,,463.599,66.039,15.470,"21Vianet Group, Inc. provides carrier-neutral ...",3451.595388,-2987.996388,324.879,138.720
8306,160938,2012.0,2242749 ONT LTD,3261.0,Concord,ON,457.415,24.055,2.300,Armtec Infrastructure Inc. manufactures and ma...,3224.339204,-2766.924204,NaN,NaN
21296,160938,2013.0,2242749 ONT LTD,3261.0,Concord,ON,455.522,24.055,1.280,Armtec Infrastructure Inc. manufactures and ma...,3269.491162,-2813.969162,457.415,-1.893

In [94]:
#create a change score (current – lagged revenues)
df3['change_score'] = df3['revt_x'] - df3['revt1']
df3.head()

,gvkey,fyear,conm,naics,city,state,revt_x,csho,prcc_c,busdesc,revt_y,devscore,revt1,change_score
6966,132602,2012.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,0.934,64.564,1.060,01 Communique Laboratory Inc. develops and mar...,3224.339204,-3223.405204,NaN,NaN
20063,132602,2013.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,1.258,65.204,0.345,01 Communique Laboratory Inc. develops and mar...,3269.491162,-3268.233162,0.934,0.324
32581,132602,2014.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,0.267,65.744,0.195,01 Communique Laboratory Inc. develops and mar...,3451.595388,-3451.328388,1.258,-0.991
6762,122519,2012.0,1-800-FLOWERS.COM,453110.0,Carle Place,NY,716.257,64.556,3.670,"1-800-FLOWERS.COM, Inc. operates a florist and...",3224.339204,-2508.082204,NaN,NaN
19868,122519,2013.0,1-800-FLOWERS.COM,453110.0,Carle Place,NY,735.497,63.868,5.410,"1-800-FLOWERS.COM, Inc. operates a florist and...",3269.491162,-2533.994162,716.257,19.240

In [225]:
df3["conm"].to_excel("output.xlsx")

In [106]:
#correlate lagged and current revenues 
correlation = df3['revt1'].corr(df3['revt_x'])
print("There is a positive {:.3f} correlation between lagged and current revenues.".format(correlation))

There is a positive 0.995 correlation between lagged and current revenues.

# Creating Dummy Variables

In [235]:
#create a binary variable for whether the company name includes “.com”, case-insensitive

company_dummy= pd.get_dummies(df3['conm'].str.contains(".com", case = False, regex = False)).iloc[:,1]

In [236]:
df4 = pd.concat([df3, company_dummy], axis = 1)
df4.sort_values(by="conm")

,gvkey,fyear,conm,naics,city,state,revt_x,csho,prcc_c,busdesc,revt_y,devscore,revt1,change_score,True
6966,132602,2012.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,0.934,64.564,1.0600,01 Communique Laboratory Inc. develops and mar...,3224.339204,-3223.405204,NaN,NaN,0
20063,132602,2013.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,1.258,65.204,0.3450,01 Communique Laboratory Inc. develops and mar...,3269.491162,-3268.233162,0.934,0.324,0
32581,132602,2014.0,01 COMMUNIQUE LABORATORY INC,511210.0,Mississauga,ON,0.267,65.744,0.1950,01 Communique Laboratory Inc. develops and mar...,3451.595388,-3451.328388,1.258,-0.991,0
6762,122519,2012.0,1-800-FLOWERS.COM,453110.0,Carle Place,NY,716.257,64.556,3.6700,"1-800-FLOWERS.COM, Inc. operates a florist and...",3224.339204,-2508.082204,NaN,NaN,1
19868,122519,2013.0,1-800-FLOWERS.COM,453110.0,Carle Place,NY,735.497,63.868,5.4100,"1-800-FLOWERS.COM, Inc. operates a florist and...",3269.491162,-2533.994162,716.257,19.240,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6940,129441,2012.0,ZYNEX INC,334510.0,Lone Tree,CO,39.666,31.148,0.6998,"Zynex, Inc. designs, manufactures, and markets...",3224.339204,-3184.673204,NaN,NaN,0
32559,129441,2014.0,ZYNEX INC,334510.0,Lone Tree,CO,11.117,31.271,0.1650,"Zynex, Inc. designs, manufactures, and markets...",3451.595388,-3440.478388,21.684,-10.567,0
25108,187576,2013.0,ZYNGA INC,511210.0,San Francisco,CA,873.266,832.309,3.8000,"Zynga Inc. develops, markets, and operates onl...",3269.491162,-2396.225162,1281.267,-408.001,0
12365,187576,2012.0,ZYNGA INC,511210.0,San Francisco,CA,1281.267,779.249,2.3600,"Zynga Inc. develops, markets, and operates onl...",3224.339204,-1943.072204,NaN,NaN,0
37211,187576,2014.0,ZYNGA INC,511210.0,San Francisco,CA,690.410,905.860,2.6600,"Zynga Inc. develops, markets, and operates onl...",3451.595388,-2761.185388,873.266,-182.856,0

In [237]:
# group on this variable and get the mean market value (prcc_c * csho) for each group

#How many companies are there in each group 
df4.groupby(True)["conm"].count()

True
0    37655
1       95
Name: conm, dtype: int64

In [238]:
# creatign new variable mean market value 
df4["mean_market_value"] = df4["prcc_c"] * df4["csho"]

#grouping company name that have".com" and looking at mean market value for both groups 
df4.groupby(True)["mean_market_value"].mean()

True
0    3623.856262
1    7531.246953
Name: mean_market_value, dtype: float64

In [239]:
print("The market value for companies with .com have mean market value of $7531")
print("The market value for companies without .com have mean market value of $3623")

The market value for companies with .com have mean market value of $7531
The market value for companies without .com have mean market value of $3623